source 'https://rubygems.org'

ruby '2.2.3'
gem 'rails', '5.2.4.2'
# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

# for Heroku deployment - as described in Ap. A of ELLS book
group :development, :test do
  gem 'factory_girl_rails', '>= 4.5.0'
  gem 'sqlite3'
  gem 'byebug'
  gem 'database_cleaner', '1.4.1'
  gem 'capybara', '2.4.4'
  gem 'launchy'
  gem 'rspec-rails', '3.5.0'
  gem 'ZenTest', '4.11.0'
end

group :test do
  gem 'simplecov', '>= 0.12.0', :require => false
  gem 'cucumber-rails', '>= 1.4.3', :require => false
  gem 'cucumber-rails-training-wheels', '>= 1.0.0'
end
group :production do
  gem 'pg'
end

# Gems used only for assets and not required
# in production environments by default.

  #gem 'therubyracer', '~> 0.12.0'
gem 'sass-rails', '~> 5.0.5'
gem 'coffee-rails', '~> 4.2.2'
gem 'uglifier', '>= 2.7.2'

gem 'jquery-rails', '>= 4.0.5'
gem 'haml'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'
